#!/bin/zsh
 
#  _   _
# | |_| |__   ___
# | __| '_ \ / _ \
# | |_| | | |  __/
#  \__|_| |_|\___|
#
#
#  ___  ___ _ __ ___  ___ _ __  ___  __ ___   _____ _ __
# / __|/ __| '__/ _ \/ _ \ '_ \/ __|/ _` \ \ / / _ \ '__|
# \__ \ (__| | |  __/  __/ | | \__ \ (_| |\ V /  __/ |
# |___/\___|_|  \___|\___|_| |_|___/\__,_| \_/ \___|_|
#
 
 # -----------------------------------------------------------
   screensaverDir="/home/$USER/Media/Screensaver/"
   EDL="${screensaverDir}/mpvscreensaver.EDL"
   fileDir="${screensaverDir}files/"
   archiveDir="${screensaverDir}archive/"
   asciA=$(cat "${screensaverDir}asci/asciA")
   asciB=$(cat "${screensaverDir}asci/asciB")
  
   numfiles=100 #number of videos per EDL
   lenVid=9 #length of each video within EDL in seconds
   theSpeed=0.9 #speed mpv will play EDL file
  # -----------------------------------------------------------
  
  
  while true; do
  
  
      clear
  
  
      # take previous EDL file and move it to Archive folder
      mv $EDL $archiveDir
  
  
      # create new EDL file with EDL header
      echo "# mpv EDL v0" >> $EDL
  
  
      wait
  
  
      # loop to generate random EDL file
      for (( i=0; i<$numfiles; ++i )); do
  
  
          # choose random file from directory
          file="$(shuf -n1 -e ${fileDir}*)"
  
  
          # determine where in video it is okay to start from.
          #     the video must be able to complete a total
          #     $lenVid seconds without video ending before then
  
          maxStart=$(mediainfo --Inform="Video;%Duration%" $file)
          maxStart=$(echo -e "($maxStart)*0.0009-${lenVid}" \
                  | bc | sed 's/\..*$//g')
  
  
          # start selected $file at anytime before $maxStart
          start=$(( $RANDOM % $maxStart ))
  
  
          # display loading text while creating EDL file
  
          clear && echo "\n\n\n\n\n\n\n\n\n"
          echo "Generating Randomized Screensaver..." | \
                  centertext
  
  
          # display the current file number as
          #     a percentage (100 files long)
          echo -e "\n$i%\n\n" | centertext
  
  
          # display a simple animation that plays in
          #     the terminal while creating EDL file
          if [ "$(( $i % 2 ))" -eq 0 ]; then
                  echo $asciA
          else
                  echo $asciB
          fi
  
  
          # take the file, the start time, and
          #     the length of the video and
          #     insert it into the last line of
          #     the new EDL file being created
          echo $file,$start,$lenVid >> $EDL
  
  
          wait
  
  
     # end this loop, move to next
     #     file until $numfiles files are looped through
     done
 
 
     # start timer
     SECONDS=0
 
 
     # use mpv to play EDL file
     #     no audio and force aspect ratio
     #     slowed down to $theSpeed
     mpv $EDL \
             --really-quiet \
             --no-audio \
             --brightness=0 \
             --speed=$theSpeed \
             --video-aspect-override=16:9
 
 
     # wait for video to end
     #     before moving to next step
     wait
 
 
     # sets the amount of seconds that
     #     have passed since the timer started
     duration=$SECONDS
 
 
     # calculate how long it should take mpv
     #     to play EDL file
     edlLength="($lenVid * $numfiles) *"
     edlLength+=" (1 - $theSpeed) +"
     edlLength+=" ($lenVid * $numfiles) - 1 / 1"
     edlLength=${$(echo "$edlLength" | bc)%.*}
 
 
     # break out of screensaver generation loop
     #     if user exits before the total EDL
     #     file has played
     if (( $duration < $edlLength )); then
            clear && break
     fi
 
 
  # end this loop - start next EDL file if
  #     user did not already break out
  done
 


